//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptiveWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EasyPost
    {
        public int PostId { get; set; }
        public string Tags { get; set; }
        public string Question { get; set; }
    }
}
